use_small_heuristics = "Default"
max_width = 100          # 与.editorconfig中的Rust部分设置对齐
hard_tabs = false        # 使用空格代替制表符，对齐.editorconfig设置
tab_spaces = 4           # 空格数量，与.editorconfig设置一致
newline_style = "Unix"   # 使用LF作为行尾，与.editorconfig一致
fn_call_width = 90       # 函数调用的最大宽度
chain_width = 80         # 链式调用的最大宽度
wrap_comments = true     # 自动换行注释
comment_width = 80       # 注释的最大宽度
normalize_comments = true# 规范化注释风格
format_code_in_doc_comments = true # 格式化文档注释中的代码
imports_granularity = "Crate" # 按Crate分组导入
group_imports = "StdExternalCrate" # 标准库和外部crate的导入分组
reorder_imports = true   # 重新排序导入
reorder_modules = true   # 重新排序模块声明
edition = "2021"
unstable_features = true
combine_control_expr = false
enum_discrim_align_threshold = 60
format_macro_matchers = true
normalize_doc_attributes = true
reorder_impl_items = true
