[package]
name = "server-bin"
authors.workspace = true
publish.workspace = true
version.workspace = true
edition.workspace = true

[[bin]]
name = "server"
path = "src/main.rs"

[dependencies]
server-initialize = { path = "../initialize" }

axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
