services:
    postgres:
        image: postgres:17.2-alpine
        container_name: soybean_postgres
        environment:
            POSTGRES_DB: soybean-admin-rust-backend
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - soybean_net
        healthcheck:
            test:
                [
                    "CMD-SHELL",
                    "pg_isready -U postgres -d soybean-admin-rust-backend",
                ]
            interval: 10s
            timeout: 5s
            retries: 5

    redis:
        image: redis:7.4-alpine
        container_name: soybean_redis
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
            - "6379:6379"
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
            - redis_data:/data
        networks:
            - soybean_net
        healthcheck:
            test: ["CMD", "redis-cli", "AUTH", "soybean", "123456", "ping"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    postgres_data:
        name: soybean_postgres_data
    redis_data:
        name: soybean_redis_data

networks:
    soybean_net:
        name: soybean_network
        driver: bridge
