# ======================================
# Core Build Configuration
# ======================================
[build]
jobs = 16
pipelining = true
rustflags = []
incremental = false

[rust]
channel = "stable"
debuginfo = 2
parallel-compiler = true
deny-warnings = true
components = ["rustc", "rust-std", "cargo", "rust-analyzer"]

# ======================================
# Development Profile
# ======================================
[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true
codegen-units = 256
rpath = false

# ======================================
# Release Profile
# ======================================
[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = "abort"
incremental = false
codegen-units = 1
rpath = false
strip = true

# ======================================
# Universal Optimizations
# ======================================
[target.'cfg(all())']
rustflags = [
    # Performance
    "-C", "target-feature=+crt-static",
    "-C", "force-frame-pointers=yes",
    "-C", "link-arg=-fuse-ld=lld",
    # Quality
    "-D", "warnings"
]

# ======================================
# Release Mode Optimizations
# ======================================
[target.'cfg(not(debug_assertions))']
rustflags = [
    # Performance
    "-C", "opt-level=3",
    "-C", "target-cpu=native",
    "-C", "codegen-units=1",
    "-C", "embed-bitcode=yes",
    # Enable dylib LTO
    "-Z", "dylib-lto"
]

# ======================================
# Architecture Optimizations (Release Only)
# ======================================
[target.'cfg(all(target_arch = "x86_64", not(debug_assertions)))']
rustflags = ["-C", "target-feature=+sse3,+ssse3,+sse4.1,+sse4.2,+avx,+avx2,+fma,+f16c,+popcnt,+fxsr,+bmi1,+bmi2"]

[target.'cfg(all(target_arch = "aarch64", not(debug_assertions)))']
rustflags = ["-C", "target-feature=+neon,+fp-armv8,+crypto,+aes,+sha2,+crc"]

# ======================================
# Documentation
# ======================================
[doc]
browser = "firefox"
opts = [
    "--enable-index-page",
    "--enable-search",
    "--document-private-items"
]
